### ISSUE TITLE
openssl_utils.c is missing include of unistd.h

### ISSUE THREAD

**Issue by tx-yubikey** [Yubico/yubico-piv-tool#398]
When updating my own yubico-piv-tool RPM package from 2.2.0 to 2.3.0 I got an error:

`openssl_utils.c:55:5: error: implicit declaration of function 'write'; did you mean 'fwrite'? [-Werror=implicit-function-declaration]`

Simply adding unistd.h fixed the RPM build:

```
$ cat ../SOURCES/yubico-piv-tool-2.3.0-unistd.patch
--- yubico-piv-tool-2.3.0/ykcs11/openssl_utils.c        2022-09-05 13:36:00.808655688 +0200
+++ yubico-piv-tool-2.3.0.rh/ykcs11/openssl_utils.c     2022-09-05 13:33:55.641814290 +0200
@@ -36,6 +36,7 @@
 #include "debug.h"
 #include <string.h>
 #include <stdio.h>
+#include <unistd.h>
 
 CK_RV do_rand_seed(CK_BYTE_PTR data, CK_ULONG len) {
   RAND_seed(data, len);
```

**Comment by qpernil** [comment]
I don't understand that error message - Line 55 looks like an empty line and there is no write call in that file (or anywhere as far as I can tell). Can you perhaps clarify ?

**Comment by tx-yubikey** [comment]
Ooops... sorry... the diff is from an RPM package.
And the fixed write() actually came from a former patch in this RPM package.
Please close it...

**Comment by qpernil** [comment]
Alright, closing this issue.
Best regards.
