### ISSUE TITLE
yubico-piv-tool v.2.0.0 fails to build with libressl 2.9.2

### ISSUE THREAD

**Issue by bK4gYuRo** [Yubico/yubico-piv-tool#229]
Excerpts from the build log:
`:info:build make[3]: Entering directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_security_yubico-piv-tool/yubico-piv-tool/work/Yubico-yubico-piv-tool-fef304d/tool'
:info:build   CC       yubico-piv-tool.o
:info:build   CC       libpiv_cmd_la-cmdline.lo
:info:build   CC       util.lo
:info:build   CC       openssl-compat.lo
:info:build In file included from yubico-piv-tool.c:45:
:info:build ./openssl-compat.h:36:6: error: conflicting types for 'EVP_PKEY_get0_RSA'
:info:build RSA *EVP_PKEY_get0_RSA(const EVP_PKEY *pkey);
:info:build      ^
:info:build /opt/local/include/openssl/evp.h:909:16: note: previous declaration is here
:info:build struct rsa_st *EVP_PKEY_get0_RSA(EVP_PKEY *pkey);
:info:build                ^
:info:build In file included from yubico-piv-tool.c:45:
:info:build ./openssl-compat.h:37:9: error: conflicting types for 'EVP_PKEY_get0_EC_KEY'
:info:build EC_KEY *EVP_PKEY_get0_EC_KEY(const EVP_PKEY *pkey);
:info:build         ^
:info:build /opt/local/include/openssl/evp.h:927:19: note: previous declaration is here
:info:build struct ec_key_st *EVP_PKEY_get0_EC_KEY(EVP_PKEY *pkey);
:info:build                   ^
:info:build 2 errors generated.
:info:build make[3]: *** [yubico-piv-tool.o] Error 1
:info:build make[3]: *** Waiting for unfinished jobs....
:info:build In file included from util.c:40:
:info:build ./openssl-compat.h:36:6: error: conflicting types for 'EVP_PKEY_get0_RSA'
:info:build RSA *EVP_PKEY_get0_RSA(const EVP_PKEY *pkey);
:info:build      ^
:info:build /opt/local/include/openssl/evp.h:909:16: note: previous declaration is here
:info:build struct rsa_st *EVP_PKEY_get0_RSA(EVP_PKEY *pkey);
:info:build                ^
:info:build In file included from util.c:40:
:info:build ./openssl-compat.h:37:9: error: conflicting types for 'EVP_PKEY_get0_EC_KEY'
:info:build EC_KEY *EVP_PKEY_get0_EC_KEY(const EVP_PKEY *pkey);
:info:build         ^
:info:build /opt/local/include/openssl/evp.h:927:19: note: previous declaration is here
:info:build struct ec_key_st *EVP_PKEY_get0_EC_KEY(EVP_PKEY *pkey);
:info:build                   ^
:info:build In file included from openssl-compat.c:10:
:info:build ./openssl-compat.h:36:6: error: conflicting types for 'EVP_PKEY_get0_RSA'
:info:build RSA *EVP_PKEY_get0_RSA(const EVP_PKEY *pkey);
:info:build      ^
:info:build /opt/local/include/openssl/evp.h:909:16: note: previous declaration is here
:info:build struct rsa_st *EVP_PKEY_get0_RSA(EVP_PKEY *pkey);
:info:build                ^
:info:build In file included from openssl-compat.c:10:
:info:build ./openssl-compat.h:37:9: error: conflicting types for 'EVP_PKEY_get0_EC_KEY'
:info:build EC_KEY *EVP_PKEY_get0_EC_KEY(const EVP_PKEY *pkey);
:info:build         ^
:info:build /opt/local/include/openssl/evp.h:927:19: note: previous declaration is here
:info:build struct ec_key_st *EVP_PKEY_get0_EC_KEY(EVP_PKEY *pkey);
:info:build                   ^
:info:build openssl-compat.c:99:6: error: conflicting types for 'EVP_PKEY_get0_RSA'
:info:build RSA *EVP_PKEY_get0_RSA(const EVP_PKEY *pkey) {
:info:build      ^
:info:build /opt/local/include/openssl/evp.h:909:16: note: previous declaration is here
:info:build struct rsa_st *EVP_PKEY_get0_RSA(EVP_PKEY *pkey);
:info:build                ^
:info:build openssl-compat.c:106:9: error: conflicting types for 'EVP_PKEY_get0_EC_KEY'
:info:build EC_KEY *EVP_PKEY_get0_EC_KEY(const EVP_PKEY *pkey) {
:info:build         ^
:info:build /opt/local/include/openssl/evp.h:927:19: note: previous declaration is here
:info:build struct ec_key_st *EVP_PKEY_get0_EC_KEY(EVP_PKEY *pkey);
:info:build                   ^
:info:build 2 errors generated.
:info:build 4 errors generated.
`

**Comment by qpernil** [comment]
OK, seems libressl has implemented some of the functions in openssl_compat.c. I will open a task to solve this, targeting the upcoming 2.0.1 release.

**Comment by qpernil** [comment]
This is now fixed on the master branch, and will be in the upcoming 2.1.0 release of yubico-piv-tool. It has been tested with libressl 2.0.6 to 3.1.0 (Only the versions available as branches in https://github.com/libressl-portable/portable have been tested)
